// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/blokus.proto

package com.zylear.proto;

public final class BlokusOuterClass {
  private BlokusOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BLOKUSAccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BLOKUSAccount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string account = 1;</code>
     */
    boolean hasAccount();
    /**
     * <code>optional string account = 1;</code>
     */
    java.lang.String getAccount();
    /**
     * <code>optional string account = 1;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>optional string password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 2;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code BLOKUSAccount}
   *
   * <pre>
   *1.0.0
   * </pre>
   */
  public  static final class BLOKUSAccount extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BLOKUSAccount)
      BLOKUSAccountOrBuilder {
    // Use BLOKUSAccount.newBuilder() to construct.
    private BLOKUSAccount(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private BLOKUSAccount() {
      account_ = "";
      password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BLOKUSAccount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              account_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              password_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zylear.proto.BlokusOuterClass.internal_static_BLOKUSAccount_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zylear.proto.BlokusOuterClass.internal_static_BLOKUSAccount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zylear.proto.BlokusOuterClass.BLOKUSAccount.class, com.zylear.proto.BlokusOuterClass.BLOKUSAccount.Builder.class);
    }

    private int bitField0_;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private volatile java.lang.Object account_;
    /**
     * <code>optional string account = 1;</code>
     */
    public boolean hasAccount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string account = 1;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          account_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string account = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>optional string password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          password_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPasswordBytes());
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAccountBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPasswordBytes());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.zylear.proto.BlokusOuterClass.BLOKUSAccount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSAccount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSAccount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSAccount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSAccount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSAccount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSAccount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSAccount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSAccount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSAccount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zylear.proto.BlokusOuterClass.BLOKUSAccount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BLOKUSAccount}
     *
     * <pre>
     *1.0.0
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BLOKUSAccount)
        com.zylear.proto.BlokusOuterClass.BLOKUSAccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zylear.proto.BlokusOuterClass.internal_static_BLOKUSAccount_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zylear.proto.BlokusOuterClass.internal_static_BLOKUSAccount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zylear.proto.BlokusOuterClass.BLOKUSAccount.class, com.zylear.proto.BlokusOuterClass.BLOKUSAccount.Builder.class);
      }

      // Construct using com.zylear.proto.BlokusOuterClass.BLOKUSAccount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        account_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zylear.proto.BlokusOuterClass.internal_static_BLOKUSAccount_descriptor;
      }

      public com.zylear.proto.BlokusOuterClass.BLOKUSAccount getDefaultInstanceForType() {
        return com.zylear.proto.BlokusOuterClass.BLOKUSAccount.getDefaultInstance();
      }

      public com.zylear.proto.BlokusOuterClass.BLOKUSAccount build() {
        com.zylear.proto.BlokusOuterClass.BLOKUSAccount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zylear.proto.BlokusOuterClass.BLOKUSAccount buildPartial() {
        com.zylear.proto.BlokusOuterClass.BLOKUSAccount result = new com.zylear.proto.BlokusOuterClass.BLOKUSAccount(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.account_ = account_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zylear.proto.BlokusOuterClass.BLOKUSAccount) {
          return mergeFrom((com.zylear.proto.BlokusOuterClass.BLOKUSAccount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zylear.proto.BlokusOuterClass.BLOKUSAccount other) {
        if (other == com.zylear.proto.BlokusOuterClass.BLOKUSAccount.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          bitField0_ |= 0x00000001;
          account_ = other.account_;
          onChanged();
        }
        if (other.hasPassword()) {
          bitField0_ |= 0x00000002;
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zylear.proto.BlokusOuterClass.BLOKUSAccount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zylear.proto.BlokusOuterClass.BLOKUSAccount) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object account_ = "";
      /**
       * <code>optional string account = 1;</code>
       */
      public boolean hasAccount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string account = 1;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            account_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string account = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string account = 1;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 1;</code>
       */
      public Builder clearAccount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 1;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        account_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            password_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 2;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BLOKUSAccount)
    }

    // @@protoc_insertion_point(class_scope:BLOKUSAccount)
    private static final com.zylear.proto.BlokusOuterClass.BLOKUSAccount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zylear.proto.BlokusOuterClass.BLOKUSAccount();
    }

    public static com.zylear.proto.BlokusOuterClass.BLOKUSAccount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<BLOKUSAccount> PARSER =
        new com.google.protobuf.AbstractParser<BLOKUSAccount>() {
      public BLOKUSAccount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new BLOKUSAccount(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BLOKUSAccount> getParserForType() {
      return PARSER;
    }

    public com.zylear.proto.BlokusOuterClass.BLOKUSAccount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BLOKUSCreateRoomOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BLOKUSCreateRoom)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string roomName = 1;</code>
     */
    boolean hasRoomName();
    /**
     * <code>optional string roomName = 1;</code>
     */
    java.lang.String getRoomName();
    /**
     * <code>optional string roomName = 1;</code>
     */
    com.google.protobuf.ByteString
        getRoomNameBytes();

    /**
     * <code>optional int32 roomType = 2;</code>
     */
    boolean hasRoomType();
    /**
     * <code>optional int32 roomType = 2;</code>
     */
    int getRoomType();
  }
  /**
   * Protobuf type {@code BLOKUSCreateRoom}
   *
   * <pre>
   *1.0.0
   * </pre>
   */
  public  static final class BLOKUSCreateRoom extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BLOKUSCreateRoom)
      BLOKUSCreateRoomOrBuilder {
    // Use BLOKUSCreateRoom.newBuilder() to construct.
    private BLOKUSCreateRoom(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private BLOKUSCreateRoom() {
      roomName_ = "";
      roomType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BLOKUSCreateRoom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              roomName_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              roomType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zylear.proto.BlokusOuterClass.internal_static_BLOKUSCreateRoom_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zylear.proto.BlokusOuterClass.internal_static_BLOKUSCreateRoom_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom.class, com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom.Builder.class);
    }

    private int bitField0_;
    public static final int ROOMNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object roomName_;
    /**
     * <code>optional string roomName = 1;</code>
     */
    public boolean hasRoomName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string roomName = 1;</code>
     */
    public java.lang.String getRoomName() {
      java.lang.Object ref = roomName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          roomName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string roomName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRoomNameBytes() {
      java.lang.Object ref = roomName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROOMTYPE_FIELD_NUMBER = 2;
    private int roomType_;
    /**
     * <code>optional int32 roomType = 2;</code>
     */
    public boolean hasRoomType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 roomType = 2;</code>
     */
    public int getRoomType() {
      return roomType_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRoomNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, roomType_);
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRoomNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, roomType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BLOKUSCreateRoom}
     *
     * <pre>
     *1.0.0
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BLOKUSCreateRoom)
        com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zylear.proto.BlokusOuterClass.internal_static_BLOKUSCreateRoom_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zylear.proto.BlokusOuterClass.internal_static_BLOKUSCreateRoom_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom.class, com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom.Builder.class);
      }

      // Construct using com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        roomName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        roomType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zylear.proto.BlokusOuterClass.internal_static_BLOKUSCreateRoom_descriptor;
      }

      public com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom getDefaultInstanceForType() {
        return com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom.getDefaultInstance();
      }

      public com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom build() {
        com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom buildPartial() {
        com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom result = new com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roomName_ = roomName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.roomType_ = roomType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom) {
          return mergeFrom((com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom other) {
        if (other == com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom.getDefaultInstance()) return this;
        if (other.hasRoomName()) {
          bitField0_ |= 0x00000001;
          roomName_ = other.roomName_;
          onChanged();
        }
        if (other.hasRoomType()) {
          setRoomType(other.getRoomType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object roomName_ = "";
      /**
       * <code>optional string roomName = 1;</code>
       */
      public boolean hasRoomName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string roomName = 1;</code>
       */
      public java.lang.String getRoomName() {
        java.lang.Object ref = roomName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            roomName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string roomName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRoomNameBytes() {
        java.lang.Object ref = roomName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string roomName = 1;</code>
       */
      public Builder setRoomName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        roomName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string roomName = 1;</code>
       */
      public Builder clearRoomName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roomName_ = getDefaultInstance().getRoomName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string roomName = 1;</code>
       */
      public Builder setRoomNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        roomName_ = value;
        onChanged();
        return this;
      }

      private int roomType_ ;
      /**
       * <code>optional int32 roomType = 2;</code>
       */
      public boolean hasRoomType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 roomType = 2;</code>
       */
      public int getRoomType() {
        return roomType_;
      }
      /**
       * <code>optional int32 roomType = 2;</code>
       */
      public Builder setRoomType(int value) {
        bitField0_ |= 0x00000002;
        roomType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 roomType = 2;</code>
       */
      public Builder clearRoomType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        roomType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BLOKUSCreateRoom)
    }

    // @@protoc_insertion_point(class_scope:BLOKUSCreateRoom)
    private static final com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom();
    }

    public static com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<BLOKUSCreateRoom> PARSER =
        new com.google.protobuf.AbstractParser<BLOKUSCreateRoom>() {
      public BLOKUSCreateRoom parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new BLOKUSCreateRoom(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BLOKUSCreateRoom> getParserForType() {
      return PARSER;
    }

    public com.zylear.proto.BlokusOuterClass.BLOKUSCreateRoom getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BLOKUSRoomNameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BLOKUSRoomName)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string roomName = 1;</code>
     */
    boolean hasRoomName();
    /**
     * <code>optional string roomName = 1;</code>
     */
    java.lang.String getRoomName();
    /**
     * <code>optional string roomName = 1;</code>
     */
    com.google.protobuf.ByteString
        getRoomNameBytes();
  }
  /**
   * Protobuf type {@code BLOKUSRoomName}
   *
   * <pre>
   *1.0.0
   * </pre>
   */
  public  static final class BLOKUSRoomName extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BLOKUSRoomName)
      BLOKUSRoomNameOrBuilder {
    // Use BLOKUSRoomName.newBuilder() to construct.
    private BLOKUSRoomName(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private BLOKUSRoomName() {
      roomName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BLOKUSRoomName(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              roomName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zylear.proto.BlokusOuterClass.internal_static_BLOKUSRoomName_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zylear.proto.BlokusOuterClass.internal_static_BLOKUSRoomName_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zylear.proto.BlokusOuterClass.BLOKUSRoomName.class, com.zylear.proto.BlokusOuterClass.BLOKUSRoomName.Builder.class);
    }

    private int bitField0_;
    public static final int ROOMNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object roomName_;
    /**
     * <code>optional string roomName = 1;</code>
     */
    public boolean hasRoomName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string roomName = 1;</code>
     */
    public java.lang.String getRoomName() {
      java.lang.Object ref = roomName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          roomName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string roomName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRoomNameBytes() {
      java.lang.Object ref = roomName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRoomNameBytes());
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRoomNameBytes());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.zylear.proto.BlokusOuterClass.BLOKUSRoomName parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSRoomName parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSRoomName parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSRoomName parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSRoomName parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSRoomName parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSRoomName parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSRoomName parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSRoomName parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zylear.proto.BlokusOuterClass.BLOKUSRoomName parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zylear.proto.BlokusOuterClass.BLOKUSRoomName prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BLOKUSRoomName}
     *
     * <pre>
     *1.0.0
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BLOKUSRoomName)
        com.zylear.proto.BlokusOuterClass.BLOKUSRoomNameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zylear.proto.BlokusOuterClass.internal_static_BLOKUSRoomName_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zylear.proto.BlokusOuterClass.internal_static_BLOKUSRoomName_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zylear.proto.BlokusOuterClass.BLOKUSRoomName.class, com.zylear.proto.BlokusOuterClass.BLOKUSRoomName.Builder.class);
      }

      // Construct using com.zylear.proto.BlokusOuterClass.BLOKUSRoomName.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        roomName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zylear.proto.BlokusOuterClass.internal_static_BLOKUSRoomName_descriptor;
      }

      public com.zylear.proto.BlokusOuterClass.BLOKUSRoomName getDefaultInstanceForType() {
        return com.zylear.proto.BlokusOuterClass.BLOKUSRoomName.getDefaultInstance();
      }

      public com.zylear.proto.BlokusOuterClass.BLOKUSRoomName build() {
        com.zylear.proto.BlokusOuterClass.BLOKUSRoomName result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zylear.proto.BlokusOuterClass.BLOKUSRoomName buildPartial() {
        com.zylear.proto.BlokusOuterClass.BLOKUSRoomName result = new com.zylear.proto.BlokusOuterClass.BLOKUSRoomName(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roomName_ = roomName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zylear.proto.BlokusOuterClass.BLOKUSRoomName) {
          return mergeFrom((com.zylear.proto.BlokusOuterClass.BLOKUSRoomName)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zylear.proto.BlokusOuterClass.BLOKUSRoomName other) {
        if (other == com.zylear.proto.BlokusOuterClass.BLOKUSRoomName.getDefaultInstance()) return this;
        if (other.hasRoomName()) {
          bitField0_ |= 0x00000001;
          roomName_ = other.roomName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zylear.proto.BlokusOuterClass.BLOKUSRoomName parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zylear.proto.BlokusOuterClass.BLOKUSRoomName) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object roomName_ = "";
      /**
       * <code>optional string roomName = 1;</code>
       */
      public boolean hasRoomName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string roomName = 1;</code>
       */
      public java.lang.String getRoomName() {
        java.lang.Object ref = roomName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            roomName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string roomName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRoomNameBytes() {
        java.lang.Object ref = roomName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string roomName = 1;</code>
       */
      public Builder setRoomName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        roomName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string roomName = 1;</code>
       */
      public Builder clearRoomName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roomName_ = getDefaultInstance().getRoomName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string roomName = 1;</code>
       */
      public Builder setRoomNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        roomName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BLOKUSRoomName)
    }

    // @@protoc_insertion_point(class_scope:BLOKUSRoomName)
    private static final com.zylear.proto.BlokusOuterClass.BLOKUSRoomName DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zylear.proto.BlokusOuterClass.BLOKUSRoomName();
    }

    public static com.zylear.proto.BlokusOuterClass.BLOKUSRoomName getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<BLOKUSRoomName> PARSER =
        new com.google.protobuf.AbstractParser<BLOKUSRoomName>() {
      public BLOKUSRoomName parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new BLOKUSRoomName(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BLOKUSRoomName> getParserForType() {
      return PARSER;
    }

    public com.zylear.proto.BlokusOuterClass.BLOKUSRoomName getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BLOKUSAccount_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BLOKUSAccount_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BLOKUSCreateRoom_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BLOKUSCreateRoom_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BLOKUSRoomName_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BLOKUSRoomName_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022proto/blokus.proto\"2\n\rBLOKUSAccount\022\017\n" +
      "\007account\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"6\n\020BLOK" +
      "USCreateRoom\022\020\n\010roomName\030\001 \001(\t\022\020\n\010roomTy" +
      "pe\030\002 \001(\005\"\"\n\016BLOKUSRoomName\022\020\n\010roomName\030\001" +
      " \001(\tB$\n\020com.zylear.protoB\020BlokusOuterCla" +
      "ss"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BLOKUSAccount_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BLOKUSAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BLOKUSAccount_descriptor,
        new java.lang.String[] { "Account", "Password", });
    internal_static_BLOKUSCreateRoom_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BLOKUSCreateRoom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BLOKUSCreateRoom_descriptor,
        new java.lang.String[] { "RoomName", "RoomType", });
    internal_static_BLOKUSRoomName_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BLOKUSRoomName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BLOKUSRoomName_descriptor,
        new java.lang.String[] { "RoomName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
