// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/Login.proto

package com.zylear.netty.contract;

public final class LoginOuterClass {
  private LoginOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 operation_code = 1;</code>
     */
    boolean hasOperationCode();
    /**
     * <code>optional int32 operation_code = 1;</code>
     */
    int getOperationCode();

    /**
     * <code>optional int32 status_code = 2;</code>
     */
    boolean hasStatusCode();
    /**
     * <code>optional int32 status_code = 2;</code>
     */
    int getStatusCode();

    /**
     * <code>optional string data = 3;</code>
     */
    boolean hasData();
    /**
     * <code>optional string data = 3;</code>
     */
    java.lang.String getData();
    /**
     * <code>optional string data = 3;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code LoginMessage}
   */
  public  static final class LoginMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LoginMessage)
      LoginMessageOrBuilder {
    // Use LoginMessage.newBuilder() to construct.
    private LoginMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private LoginMessage() {
      operationCode_ = 0;
      statusCode_ = 0;
      data_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              operationCode_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              statusCode_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              data_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zylear.netty.contract.LoginOuterClass.internal_static_LoginMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zylear.netty.contract.LoginOuterClass.internal_static_LoginMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zylear.netty.contract.LoginOuterClass.LoginMessage.class, com.zylear.netty.contract.LoginOuterClass.LoginMessage.Builder.class);
    }

    private int bitField0_;
    public static final int OPERATION_CODE_FIELD_NUMBER = 1;
    private int operationCode_;
    /**
     * <code>optional int32 operation_code = 1;</code>
     */
    public boolean hasOperationCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 operation_code = 1;</code>
     */
    public int getOperationCode() {
      return operationCode_;
    }

    public static final int STATUS_CODE_FIELD_NUMBER = 2;
    private int statusCode_;
    /**
     * <code>optional int32 status_code = 2;</code>
     */
    public boolean hasStatusCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 status_code = 2;</code>
     */
    public int getStatusCode() {
      return statusCode_;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object data_;
    /**
     * <code>optional string data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string data = 3;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string data = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, operationCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, statusCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, operationCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, statusCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.zylear.netty.contract.LoginOuterClass.LoginMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zylear.netty.contract.LoginOuterClass.LoginMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zylear.netty.contract.LoginOuterClass.LoginMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zylear.netty.contract.LoginOuterClass.LoginMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zylear.netty.contract.LoginOuterClass.LoginMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zylear.netty.contract.LoginOuterClass.LoginMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zylear.netty.contract.LoginOuterClass.LoginMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zylear.netty.contract.LoginOuterClass.LoginMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zylear.netty.contract.LoginOuterClass.LoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zylear.netty.contract.LoginOuterClass.LoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zylear.netty.contract.LoginOuterClass.LoginMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginMessage)
        com.zylear.netty.contract.LoginOuterClass.LoginMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zylear.netty.contract.LoginOuterClass.internal_static_LoginMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zylear.netty.contract.LoginOuterClass.internal_static_LoginMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zylear.netty.contract.LoginOuterClass.LoginMessage.class, com.zylear.netty.contract.LoginOuterClass.LoginMessage.Builder.class);
      }

      // Construct using com.zylear.netty.contract.LoginOuterClass.LoginMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        operationCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        statusCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zylear.netty.contract.LoginOuterClass.internal_static_LoginMessage_descriptor;
      }

      public com.zylear.netty.contract.LoginOuterClass.LoginMessage getDefaultInstanceForType() {
        return com.zylear.netty.contract.LoginOuterClass.LoginMessage.getDefaultInstance();
      }

      public com.zylear.netty.contract.LoginOuterClass.LoginMessage build() {
        com.zylear.netty.contract.LoginOuterClass.LoginMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zylear.netty.contract.LoginOuterClass.LoginMessage buildPartial() {
        com.zylear.netty.contract.LoginOuterClass.LoginMessage result = new com.zylear.netty.contract.LoginOuterClass.LoginMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.operationCode_ = operationCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.statusCode_ = statusCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zylear.netty.contract.LoginOuterClass.LoginMessage) {
          return mergeFrom((com.zylear.netty.contract.LoginOuterClass.LoginMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zylear.netty.contract.LoginOuterClass.LoginMessage other) {
        if (other == com.zylear.netty.contract.LoginOuterClass.LoginMessage.getDefaultInstance()) return this;
        if (other.hasOperationCode()) {
          setOperationCode(other.getOperationCode());
        }
        if (other.hasStatusCode()) {
          setStatusCode(other.getStatusCode());
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000004;
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zylear.netty.contract.LoginOuterClass.LoginMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zylear.netty.contract.LoginOuterClass.LoginMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int operationCode_ ;
      /**
       * <code>optional int32 operation_code = 1;</code>
       */
      public boolean hasOperationCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 operation_code = 1;</code>
       */
      public int getOperationCode() {
        return operationCode_;
      }
      /**
       * <code>optional int32 operation_code = 1;</code>
       */
      public Builder setOperationCode(int value) {
        bitField0_ |= 0x00000001;
        operationCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 operation_code = 1;</code>
       */
      public Builder clearOperationCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operationCode_ = 0;
        onChanged();
        return this;
      }

      private int statusCode_ ;
      /**
       * <code>optional int32 status_code = 2;</code>
       */
      public boolean hasStatusCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 status_code = 2;</code>
       */
      public int getStatusCode() {
        return statusCode_;
      }
      /**
       * <code>optional int32 status_code = 2;</code>
       */
      public Builder setStatusCode(int value) {
        bitField0_ |= 0x00000002;
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status_code = 2;</code>
       */
      public Builder clearStatusCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        statusCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>optional string data = 3;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 3;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LoginMessage)
    }

    // @@protoc_insertion_point(class_scope:LoginMessage)
    private static final com.zylear.netty.contract.LoginOuterClass.LoginMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zylear.netty.contract.LoginOuterClass.LoginMessage();
    }

    public static com.zylear.netty.contract.LoginOuterClass.LoginMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LoginMessage>
        PARSER = new com.google.protobuf.AbstractParser<LoginMessage>() {
      public LoginMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new LoginMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<LoginMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginMessage> getParserForType() {
      return PARSER;
    }

    public com.zylear.netty.contract.LoginOuterClass.LoginMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoginMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024protobuf/Login.proto\"I\n\014LoginMessage\022\026" +
      "\n\016operation_code\030\001 \001(\005\022\023\n\013status_code\030\002 " +
      "\001(\005\022\014\n\004data\030\003 \001(\tB,\n\031com.zylear.netty.co" +
      "ntractB\017LoginOuterClass"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LoginMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LoginMessage_descriptor,
        new java.lang.String[] { "OperationCode", "StatusCode", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
